### ISSUE TITLE
Chained Credentials RFC (104) Data provenance is not to be mistaken for provenance of authority (delegation)

### ISSUE THREAD

**Issue by RieksJ** [hyperledger/aries-rfcs#709] opened 2022-01-10 13:39 UTC
The first sentence in the section [Delegation as provenance of authority (of the README file)](https://github.com/hyperledger/aries-rfcs/tree/main/concepts/0104-chained-credentials#delegation-as-provenance-of-authority) states: "Delegation can be modeled as a data provenance issue, where the data in question is an authorization." 

I disagree. Attesting stuff (stuff would be: statements), and pointing to the sources for that is one thing. Delegating stuff (stuff would be: rights and/or duties), and pointing to the source of the right, is quite different. Whereas the right to say things is commonly acknowledged (it is a human right), this is not the case for the right to pass rights/duties on. If I have the right to drive a car, this does not imply that I can pass on this right to anyone else.

I suggest to change the text of the README to accommodate for this.

**Comment by swcurran** [comment] 2022-01-10 14:41
I think this nuance is created because of a core difference in the meaning of AnonCreds and W3C Verifiable Credentials.  In AnonCreds both the Issuer and the Holder are cryptographic participants in the issuance of the credential ("Issuer Alice said X to Holder Bob") vs. in the W3C Verifiable Credential model where only the Issuer is ("Issuer Alice said X about Subject Bob" -- no reference to the holder).

Inherently in the AnonCreds case, the possession of the data -- proof that you are the Holder as intended by the Issuer -- makes it so that possession does matter. Thus if the semantic meaning of the specific credential is that it is an authority, then prove of being the holder is a delegation as noted in this RFC.

Note that in the W3C model, if the semantic meaning of the credential is that the Issuer grants authority to the Subject AND the Holder proves they are the Subject, then the same result is achieved. That extra step is required.

In the "chained credential" model -- the Holder becoming an Issuer of the Credential to another Holder provides a further delegation.

**Comment by RieksJ** [comment] 2022-01-10 15:21
The issue is not whether or not the holder (to which the credential is issued) is the subject of (claims in) the issued credential. The issue is that a claim is a conceptually different notion than an authority. 

If I can pass a claim about me to you, then all I do is pass a statement of the claim's issuer to you. For example, some authority could issue a credential saying that I have the right to drive a car. That right, however, does not automatically entitle me to delegate it to you. And the same goes for contract negotiations and anything else. A right (permission, authorization, duty) is NOT a statement that you can pass on. 

That is not to say you cannot have chained delegations. But that requires a different kind of chain: you must not prove that the data originated from a specific source/issuer, but you must prove that this source/issuer is properly entitled to provide you with that right. And that source/issuer itself may not even need to have that right itself (the officer that issues my driving license is not required to have a driving license itself).

**Comment by swcurran** [comment] 2022-01-10 15:39
Ah...now we get into a debate about what is a Verifiable Credential vs. other terms for the concepts of inherent in VCs.  In the W3C VC model, there is considerable opinion on what such a chunk of data -- particular the focus on "subject".  So using a W3C VC for other purposes (such as authorization) is out of bounds.  And that is fine.

That said, in AnonCreds there is not the same opinion defined in the specification. It is much more about "Verifiable Data", where such data can be used as a (lower-case) verifiable credential, but it can also be used for other purposes, including as an authority.  What is proven by an AnonCreds presentation:

1. Who issued the credential.
2. That it was issued to the Holder/Prover
3. That is was not tampered with.
4. (Optional) that it was not revoked.

Those attributes are needed for verifiable credentials, but can also be used for other purposes where those same properties are needed.  It just so happens that one such other use is with authority granted by the issuer to the holder.  Agree that is not a "verifiable credential", but my argument is that it needs the same properties. 

Thus, if we back away from the rigid use of "subject" and just apply the "verifiable" aspects to data, the delegation  model becomes a possible use case, including the chaining of such verifiable data to enable delegation of authority.

There is a long discussion about the pros and cons of this in a famed W3C CCG chain started by Kaliya Young here: https://lists.w3.org/Archives/Public/public-credentials/2020Dec/0023.html

**Comment by swcurran** [comment] 2022-01-10 16:24
Yes -- that is what is intended.  The intent of the issuer in issuing the credential must be known -- the schema and the intended semantics of using that specific credential. Which gets back to governance.

**Comment by RieksJ** [comment] 2022-01-11 07:38
Cool. It implies that the embedding of accreditation and certification credentials as proposed by the [Decentralized SSI Governance paper](https://docs.google.com/document/d/1FQTxzQ9z9Tv-WA_UYyfF8AgvEfBYBWRgGvSdjsQof4s/edit#heading=h.39xr6sf6t5l3) is then fully in line with this RFC. That's good enough for me to have this issue closed.

**Comment by swcurran** [comment] 2022-01-11 17:09
Excellent paper -- we share that one with collaborators.

Closing this issue per note above.

**Closed by swcurran** 2022-01-11 17:09 UTC
